<a href="https://colab.research.google.com/github/LaxmikantRakhade/Machine_Learning_Practicals/blob/main/Practical_7_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Laxmikant Rakhade (CS23128)**

**Aim: To applay support vector machine for classification and analyze the impact of different kernels on model accuracy**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path="/content/drive/MyDrive/ML_DATASETS/pulsar_stars - pulsar_stars.csv"
df=pd.read_csv(path)
df.head(5)

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17898 entries, 0 to 17897
Data columns (total 9 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Mean of the integrated profile                17898 non-null  float64
 1   Standard deviation of the integrated profile  17898 non-null  float64
 2   Excess kurtosis of the integrated profile     17898 non-null  float64
 3   Skewness of the integrated profile            17898 non-null  float64
 4   Mean of the DM-SNR curve                      17898 non-null  float64
 5   Standard deviation of the DM-SNR curve        17898 non-null  float64
 6   Excess kurtosis of the DM-SNR curve           17898 non-null  float64
 7   Skewness of the DM-SNR curve                  17898 non-null  float64
 8   target_class                                  17898 non-null  int64
dtypes: float64(8), int64(1)
memory usage: 1.2 MB

In [ ]:
df.describe()

,Mean of the integrated profile,Standard deviation of the integrated profile,Excess kurtosis of the integrated profile,Skewness of the integrated profile,Mean of the DM-SNR curve,Standard deviation of the DM-SNR curve,Excess kurtosis of the DM-SNR curve,Skewness of the DM-SNR curve,target_class
count,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000,17898.000000
mean,111.079968,46.549532,0.477857,1.770279,12.614400,26.326515,8.303556,104.857709,0.091574
std,25.652935,6.843189,1.064040,6.167913,29.472897,19.470572,4.506092,106.514540,0.288432
min,5.812500,24.772042,-1.876011,-1.791886,0.213211,7.370432,-3.139270,-1.976976,0.000000
25%,100.929688,42.376018,0.027098,-0.188572,1.923077,14.437332,5.781506,34.960504,0.000000
50%,115.078125,46.947479,0.223240,0.198710,2.801839,18.461316,8.433515,83.064556,0.000000
75%,127.085938,51.023202,0.473325,0.927783,5.464256,28.428104,10.702959,139.309330,0.000000
max,192.617188,98.778911,8.069522,68.101622,223.392141,110.642211,34.539844,1191.000837,1.000000

In [ ]:
df.shape

(17898, 9)

In [ ]:
df.isnull().sum()

Mean of the integrated profile                  0
Standard deviation of the integrated profile    0
Excess kurtosis of the integrated profile       0
Skewness of the integrated profile              0
Mean of the DM-SNR curve                        0
Standard deviation of the DM-SNR curve          0
Excess kurtosis of the DM-SNR curve             0
Skewness of the DM-SNR curve                    0
target_class                                    0
dtype: int64

In [ ]:
df.columns

Index(['Mean of the integrated profile',
       'Standard deviation of the integrated profile',
       'Excess kurtosis of the integrated profile',
       'Skewness of the integrated profile', 'Mean of the DM-SNR curve',
       'Standard deviation of the DM-SNR curve',
       'Excess kurtosis of the DM-SNR curve', 'Skewness of the DM-SNR curve',
       'target_class'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.replace(' ', '_')
df.head()

,Mean_of_the_integrated_profile,Standard_deviation_of_the_integrated_profile,Excess_kurtosis_of_the_integrated_profile,Skewness_of_the_integrated_profile,Mean_of_the_DM-SNR_curve,Standard_deviation_of_the_DM-SNR_curve,Excess_kurtosis_of_the_DM-SNR_curve,Skewness_of_the_DM-SNR_curve,target_class
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225,0
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580,0
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909,0
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661,0
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306,0

In [ ]:
df.rename(columns={'Mean_of_the_integrated_profile': 'Mean_IP', 'Standard_deviation_of_the_integrated_profile': 'Std_Dev_IP','Excess_kurtosis_of_the_integrated_profile': 'Excess_Kurtosis_IP','Skewness_of_the_integrated_profile':'Skewness_IP','Mean_of_the_DM-SNR_curve':'Mean_dmsnr','Standard_deviation_of_the_DM-SNR_curve':'Std_dev_dmsnr','Excess_kurtosis_of_the_DM-SNR_curve':'Excess_kurtosis_dmsnr','Skewness_of_the_DM-SNR_curve':'Skewness_dmsnr','target_class':'target'}, inplace=True)

In [ ]:
df.columns

Index(['Mean_IP', 'Std_Dev_IP', 'Excess_Kurtosis_IP', 'Skewness_IP',
       'Mean_dmsnr', 'Std_dev_dmsnr', 'Excess_kurtosis_dmsnr',
       'Skewness_dmsnr', 'target'],
      dtype='object')

In [ ]:
X = df.drop(columns=['target'])
y = df['target']

In [ ]:
X.head()

,Mean_IP,Std_Dev_IP,Excess_Kurtosis_IP,Skewness_IP,Mean_dmsnr,Std_dev_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
X = pd.get_dummies(X,dtype = int)

In [ ]:
X.head()

,Mean_IP,Std_Dev_IP,Excess_Kurtosis_IP,Skewness_IP,Mean_dmsnr,Std_dev_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr
0,140.562500,55.683782,-0.234571,-0.699648,3.199833,19.110426,7.975532,74.242225
1,102.507812,58.882430,0.465318,-0.515088,1.677258,14.860146,10.576487,127.393580
2,103.015625,39.341649,0.323328,1.051164,3.121237,21.744669,7.735822,63.171909
3,136.750000,57.178449,-0.068415,-0.636238,3.642977,20.959280,6.896499,53.593661
4,88.726562,40.672225,0.600866,1.123492,1.178930,11.468720,14.269573,252.567306

In [ ]:
X = df.iloc[:,3:-1]
X = pd.get_dummies(X, dtype=int)
X

,Skewness_IP,Mean_dmsnr,Std_dev_dmsnr,Excess_kurtosis_dmsnr,Skewness_dmsnr
0,-0.699648,3.199833,19.110426,7.975532,74.242225
1,-0.515088,1.677258,14.860146,10.576487,127.393580
2,1.051164,3.121237,21.744669,7.735822,63.171909
3,-0.636238,3.642977,20.959280,6.896499,53.593661
4,1.123492,1.178930,11.468720,14.269573,252.567306
...,...,...,...,...,...
17893,-0.738123,1.296823,12.166062,15.450260,285.931022
17894,0.323061,16.409699,44.626893,2.945244,8.297092
17895,-0.743025,21.430602,58.872000,2.499517,4.595173
17896,-0.024789,1.946488,13.381731,10.007967,134.238910
17897,0.089520,188.306020,64.712562,-1.597527,1.429475

In [ ]:
y=df.iloc[:,-1]
print(y)

0        0
1        0
2        0
3        0
4        0
        ..
17893    0
17894    0
17895    0
17896    0
17897    0
Name: target, Length: 17898, dtype: int64

In [ ]:
X.shape

(17898, 5)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=42)
X_train.shape,X_test.shape

((12528, 5), (5370, 5))

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[-0.2885854 , -0.32101331, -0.40338108, -0.19481754, -0.37780071],
       [ 0.25938061, -0.34699026, -0.44578706,  0.23837256, -0.02857034],
       [-0.33434359, -0.33538534, -0.2004973 ,  0.038556  , -0.29531727],
       ...,
       [-0.21670413, -0.40151363, -0.75001383,  1.92294752,  1.91898259],
       [-0.32298516, -0.29769052, -0.24457614, -0.20616758, -0.4040674 ],
       [-0.25669812, -0.40205011, -0.74159513,  2.05677923,  2.08022728]])

In [ ]:
y_train

12223    0
1919     0
2753     0
17220    0
12110    0
        ..
11284    0
11964    0
5390     0
860      0
15795    0
Name: target, Length: 12528, dtype: int64

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
svc=SVC()
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with default hyperparameters : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with default hyperparameters : 0.9737

In [ ]:
print('Confusion Matrix')
cm=confusion_matrix(y_pred,y_test)
print(confusion_matrix(y_pred,y_test))

Confusion Matrix
[[4864  121]
 [  20  365]]

In [ ]:
import numpy as np

# Define the confusion matrix
cm = np.array([[4864, 121],
               [20, 365]])

# Calculate accuracy
accuracy = (cm[0,0] + cm[1,1]) / np.sum(cm)
print(f"Accuracy: {accuracy:.4f}")
# Output: Accuracy: 0.9737

Accuracy: 0.9737

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      4884
           1       0.95      0.75      0.84       486

    accuracy                           0.97      5370
   macro avg       0.96      0.87      0.91      5370
weighted avg       0.97      0.97      0.97      5370

In [ ]:
svc=SVC(C=100.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=100.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=100.0 : 0.9743

In [ ]:
svc=SVC(C=1000.0)
svc.fit(X_train,y_train)
y_pred=svc.predict(X_test)
print('Model accuracy score with rbf kernel and C=1000.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with rbf kernel and C=1000.0 : 0.9750

In [ ]:
linear_svc=SVC(kernel='linear',C=1.0)
linear_svc.fit(X_train,y_train)
y_pred_test=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=1.0 : 0.9750

In [ ]:
linear_svc=SVC(kernel='linear',C=100.0)
linear_svc.fit(X_train,y_train)
y_pred_test=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=100.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=100.0 : 0.9750

In [ ]:
linear_svc=SVC(kernel='linear',C=1000.0)
linear_svc.fit(X_train,y_train)
y_pred_test=linear_svc.predict(X_test)
print('Model accuracy score with linear kernel and C=1000.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with linear kernel and C=1000.0 : 0.9750

In [ ]:
poly_svc=SVC(kernel='poly',C=1.0)
poly_svc.fit(X_train,y_train)
y_pred_test=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=1.0 : 0.9750

In [ ]:
poly_svc=SVC(kernel='poly',C=100.0)
poly_svc.fit(X_train,y_train)
y_pred_test=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=100.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=100.0 : 0.9750

In [ ]:
poly_svc=SVC(kernel='poly',C=1000.0)
poly_svc.fit(X_train,y_train)
y_pred_test=poly_svc.predict(X_test)
print('Model accuracy score with polynomial kernel and C=1000.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with polynomial kernel and C=1000.0 : 0.9750

In [ ]:
sigmoid_svc=SVC(kernel='sigmoid',C=1.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.9140

In [ ]:
sigmoid_svc=SVC(kernel='sigmoid',C=100.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=100.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=100.0 : 0.9132

In [ ]:
sigmoid_svc=SVC(kernel='sigmoid',C=1000.0)
sigmoid_svc.fit(X_train,y_train)
y_pred=sigmoid_svc.predict(X_test)
print('Model accuracy score with sigmoid kernel and C=1000.0 : {0:0.4f}' .format(accuracy_score(y_test,y_pred)))

Model accuracy score with sigmoid kernel and C=1000.0 : 0.9132

In [ ]:
tn, fp, fn, tp = cm.ravel()

print(f"True Negative (TN): {tn}")
print(f"False Positive (FP): {fp}")
print(f"False Negative (FN): {fn}")
print(f"True Positive (TP): {tp}")

True Negative (TN): 4864
False Positive (FP): 121
False Negative (FN): 20
True Positive (TP): 365